apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-auto-deployer
  namespace: production
  labels:
    app: git-auto-deployer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: git-auto-deployer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: git-auto-deployer
    spec:
      containers:
        - name: app
          image: raviteja182/git-auto-deployer:latest
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              value: "1.0.0"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10